steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/booking-data-388605/gmail-bq/scheduler', '-f', 'Dockerfile.scheduler', '.']
images: ['asia-northeast1-docker.pkg.dev/booking-data-388605/gmail-bq/scheduler']
